<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TbBukuTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('tb_buku')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('tb_buku')->insert([

            /*
            ===============================
            KATEGORI 1 - NOVEL
            ===============================
            */

            [
                'id_buku' => 'B001',
                'judul_buku' => 'Bumi',
                'pengarang' => 'Tere Liye',
                'penerbit' => 'Gramedia Pustaka Utama',
                'th_terbit' => '2014',
                'stok' => 3,
                'id_kategori' => 1,
                'penyunting' => 'Tim Editor Gramedia',
                'edisi' => 'Cetakan ke-1',
                'deskripsi_fisik' => '440 halaman ; 20 cm',
                'isbn' => '9786020331218',
                'bahasa' => 'Indonesia',
                'call_number' => '813 TER b',
                'sinopsis' => 'Raib memiliki kemampuan menghilang dan menemukan dunia paralel.',
                'foto' => 'cover_buku/bumi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B002',
                'judul_buku' => 'Bulan',
                'pengarang' => 'Tere Liye',
                'penerbit' => 'Gramedia Pustaka Utama',
                'th_terbit' => '2015',
                'stok' => 3,
                'id_kategori' => 1,
                'penyunting' => 'Tim Editor Gramedia',
                'edisi' => 'Cetakan ke-1',
                'deskripsi_fisik' => '400 halaman ; 20 cm',
                'isbn' => '9786020331676',
                'bahasa' => 'Indonesia',
                'call_number' => '813 TER b',
                'sinopsis' => 'Petualangan Raib dan kawan-kawan berlanjut.',
                'foto' => 'cover_buku/bulan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B003',
                'judul_buku' => 'Matahari',
                'pengarang' => 'Tere Liye',
                'penerbit' => 'Gramedia Pustaka Utama',
                'th_terbit' => '2016',
                'stok' => 3,
                'id_kategori' => 1,
                'penyunting' => 'Tim Editor Gramedia',
                'edisi' => 'Cetakan ke-1',
                'deskripsi_fisik' => '428 halaman ; 20 cm',
                'isbn' => '9786020332741',
                'bahasa' => 'Indonesia',
                'call_number' => '813 TER m',
                'sinopsis' => 'Rahasia klan Matahari mulai terungkap.',
                'foto' => 'cover_buku/matahari.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B004',
                'judul_buku' => 'Bandung After Rain',
                'pengarang' => 'Wulan Nur Amalia',
                'penerbit' => 'Black Swan Books',
                'th_terbit' => '2024',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Feby Noer Masyitoh & Lovita Cendana',
                'edisi' => 'Cetakan kedua; Cetakan kelima',
                'deskripsi_fisik' => '282 Halaman ; 19 cm',
                'isbn' => '9786231031433',
                'bahasa' => 'Indonesia',
                'call_number' => '813 WUL b',
                'sinopsis' => 'Bandung, romansa, dan Ra. Hampir di setiap sudut di Kota Bandung menggambarkan kenangan manis yang Hema lakukan bersama Ra—mantan kekasihnya. 6 tahun lebih memadu kasih, tidak lantas membuat hubungan Hema dan Ra berakhir indah. Nyatanya, hubungan mereka usai tepat sebulan sebelum hari jadi mereka yang ke-7.',
                'foto' => 'cover_buku/bandung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B005',
                'judul_buku' => '3726 MDPL',
                'pengarang' => 'Nurwina Sari',
                'penerbit' => 'Romancious',
                'th_terbit' => '2024',
                'stok' => 1,
                'id_kategori' => 1,
                'penyunting' => 'Zafira Salsabila',
                'edisi' => 'Cetakan kedua',
                'deskripsi_fisik' => '280 Halaman ; 19 cm',
                'isbn' => '9786233102599',
                'bahasa' => 'Indonesia',
                'call_number' => '813 NUR t',
                'sinopsis' => 'Selain disibukkan dengan skripsi, Rangga, Ketua Panitia OSPEK Fakultas Kehutanan 2023 itu juga menyibukkan dirinya dengan mengagumi Andini. Seorang mahasiswi yang bercita-cita bisa mendaki Gunung Rinjani, sekaligus adik tingkat yang ia sebut sebagai manusia favorit.',
                'foto' => 'cover_buku/3726.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B006',
                'judul_buku' => 'Laut Bercerita',
                'pengarang' => 'Leila S. Chudori',
                'penerbit' => 'Kepustakaan Populer Gramedia',
                'th_terbit' => '2022',
                'stok' => 3,
                'id_kategori' => 1,
                'penyunting' => 'Endah Sulwesi & Christina M. Udian',
                'edisi' => 'Cetakan ke empat puluh dua',
                'deskripsi_fisik' => '379 halaman ; 20 cm.',
                'isbn' => '9786024246945',
                'bahasa' => 'Indonesia',
                'call_number' => '813 LEI l ; 899.221 3 LEI l',
                'sinopsis' => 'Jakarta, 2000 Asmara Jati, adik Biru Laut, beserta Tim Komisi Orang Hilang yang dipimpin Aswin Pradana mencoba mencari jejak mereka yang hilang serta merekam dan mempelajari testimoni mereka yang kembali. Anjani, kekasih Laut, para orangtua dan istri aktivis yang hilang menuntut kejelasan tentang anggota keluarga mereka. Sementara Biru Laut, dari dasar laut yang sunyi bercerita kepada kita, kepada dunia tentang apa yang terjadi pada dirinya dan kawan-kawannya. Laut Bercerita, novel terbaru Leila S. Chudori, bertutur tentang kisah keluarga yang kehilangan, sekumpulan sahabat yang merasakan kekosongan di dada, sekelompok orang yang gemar menyiksa dan lancar berkhianat, sejumlah keluarga yang mencari kejelasan makam anaknya, dan tentang cinta yang tak akan luntur.',
                'foto' => 'cover_buku/laut.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B007',
                'judul_buku' => 'Casablanca',
                'pengarang' => 'Dahlian',
                'penerbit' => 'GagasMedia',
                'th_terbit' => '2014',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Yooki',
                'edisi' => 'Cetakan pertama',
                'deskripsi_fisik' => '336 Halaman ; 19 cm',
                'isbn' => '9797807126',
                'bahasa' => 'Indonesia',
                'call_number' => '813 DAH c',
                'sinopsis' => 'Mengisahkan Vanda, wanita yang bimbang dengan rencana pernikahannya dan melarikan diri ke Casablanca, Maroko. Di sana, ia bertemu Laz, pria yang membuat hatinya bimbang antara kembali ke tunangannya atau mengikuti kata hati di kota eksotis tersebut.',
                'foto' => 'cover_buku/casablanca.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B008',
                'judul_buku' => 'Ceros dan Batozar',
                'pengarang' => 'Tere Liye',
                'penerbit' => 'PT Sabak Grip Nusantara',
                'th_terbit' => '2024',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Triana Rahmawati',
                'edisi' => 'Cetakan kesepuluh',
                'deskripsi_fisik' => '359 halaman ; 20 cm',
                'isbn' => '9786239987800',
                'bahasa' => 'Indonesia',
                'call_number' => '813 TER c',
                'sinopsis' => 'Awalnya kami hanya mengikuti karyawisata biasa seperti murid-murid sekolah lain. Hingga Ali, dengan kejeniusan dan keisengannya, memutuskan menyelidiki sebuah ruangan kuno. Kami tiba di bagian dunia paralel lainnya, menemui petarung kuat, mendapat kekuatan baru serta teknik-teknik menakjubkan. Dunia paralel ternyata sangat luas, dengan begitu banyak orang hebat di dalamnya. Kisah ini tentang petualangan tiga sahabat. Raib bisa menghilang. Seli bisa mengeluarkan petir. Dan Ali bisa melakukan apa saja.',
                'foto' => 'cover_buku/ceros&batozar.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B009',
                'judul_buku' => 'Laskar Pelangi',
                'pengarang' => 'Andrea Hirata',
                'penerbit' => 'Bentang',
                'th_terbit' => '2024',
                'stok' => 3,
                'id_kategori' => 1,
                'penyunting' => 'Suhindrati A. Shinta',
                'edisi' => 'Cetakan keenam',
                'deskripsi_fisik' => '528 halaman ; 21 cm',
                'isbn' => '9789791227186',
                'bahasa' => 'Indonesia',
                'call_number' => '813 HIR l',
                'sinopsis' => 'Begitu banyak hal menakjubkan yang terjadi dalam masa kecil para anggota Laskar Pelangi. Sebelas orang anak melayu Nelitong yang luar biasa initak menyerah walau keadaan tak bersimpati pada mereka. Salami ironisnya kehidupan mereka, kejujuran pemikiran mereka, indahnya petualangan mereka, dan temukan diri anda tertawa, menangis, dan tersentuh saat membaca setiap lembarnya. Novel ini dipersembahkan buat mereka yang meyakini the magic of childhood memories, dan khususnya juga buat siapa saja yang masih percaya akan adanya pintu keajaiban lain untuk mengubah dunia pendidikan.',
                'foto' => 'cover_buku/laskarpelangi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B010',
                'judul_buku' => 'Perahu Kertas',
                'pengarang' => 'Dee Lestari',
                'penerbit' => 'Benteng Pustaka',
                'th_terbit' => '2012',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Hermawan Aksan',
                'edisi' => 'Cetakan pertama',
                'deskripsi_fisik' => '556 halaman ; 18 cm',
                'isbn' => '978-602-291-095-4',
                'bahasa' => 'Indonesia',
                'call_number' => '813 DEE p ; 813 LES p',
                'sinopsis' => 'Menceritakan pasang surut hubungan dua anak manusia yaitu Kugy dan Keenan. Kugy selalu menulis curahan hatinya pada selembar kertas lalu dibuat menjadi perahu dan dihanyutkan ke air.',
                'foto' => 'cover_buku/laskarpelangi.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B011',
                'judul_buku' => 'Fourth Monkey',
                'pengarang' => 'Barker J.D',
                'penerbit' => 'Bhuana Sastra',
                'th_terbit' => '2025',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Ani Nuraini Syahara',
                'edisi' => 'Cetakan ketiga',
                'deskripsi_fisik' => '508 halaman ; 20 cm',
                'isbn' => '9786230420511',
                'bahasa' => 'Indonesia',
                'call_number' => '823 BAR f',
                'sinopsis' => 'Tewasnya seorang pria yang tertabrak—entah murni kecelakaan atau sengaja menabrakkan diri—menyisakan tanda tanya besar. Pasalnya, ia membawa sebuah kotak berisi potongan telinga. Disinyalir, ia adalah Pembunuh Empat Monyet, buron polisi selama hampir lima tahun. Dengan dalih filosofi Tiga Monyet Bijak, ia selalu memotong telinga, lidah, dan mencongkel mata korban-korbannya sebelum membunuhnya. Polisi dan detektif pun berusaha menguak kebenarannya lewat barang bukti yang tertinggal, termasuk buku harian tentang masa kecil sang pembunuh. Sementara itu, di satu tempat entah di mana, seorang gadis sedang berusaha bertahan hidup dengan satu telinga.',
                'foto' => 'cover_buku/fourthmonkey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B012',
                'judul_buku' => 'Nadira',
                'pengarang' => 'Leila S. Chudori',
                'penerbit' => 'Kepustakaan Populer Gramedia',
                'th_terbit' => '2025',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Endah Sulwesi',
                'edisi' => 'Cetakan kesebelas',
                'deskripsi_fisik' => '321 halaman ; 20 cm',
                'isbn' => '9786024242725',
                'bahasa' => 'Indonesia',
                'call_number' => '813 LEI n ; 899.221 3 LEI n',
                'sinopsis' => 'DI SEBUAH pagi yang murung, Nadira Suwandi menemukan ibunya tewas bunuh diri. Kematian sang ibu, Kemala Yunus, seorang perempuan yang dikenal sangat ekspresif, berpikiran bebas, dan selalu bertarung mencari diri itu, sungguh mengejutkan. Tewasnya Kemala kemudian mempengaruhi kehidupan Nadira sebagai seorang anak ("Melukis Langit"); seorang wartawan ("Tasbih"); seorang kekasih ("Ciuman Terpanjang"); seorang istri, hingga akhirnya membawa Nadira kepada sebuah penjelajahan ke dunia baru, dunia seksualitas yang tak pernah disentuhnya ("Kirana").',
                'foto' => 'cover_buku/nadira.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B013',
                'judul_buku' => 'Bekisar Merah',
                'pengarang' => 'Ahmad Tohari',
                'penerbit' => 'Gramedia Pustaka Utama',
                'th_terbit' => '2025',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Eka Pudjawati',
                'edisi' => 'Cetakan kesebelas',
                'deskripsi_fisik' => '360 halaman ; 20 cm',
                'isbn' => '9786020601762',
                'bahasa' => 'Indonesia',
                'call_number' => '813 AHM b',
                'sinopsis' => 'Novel Bekisar Merah ditulis oleh penulis terkenal Indonesia, yaitu Ahmad Tohari. Tulisannya yang menakjubkan mampu menggambarkan pandangan khas desa dengan baik melalui uraian kalimatnya. Kemampuannya dalam menulis sudah tidak diragukan lagi, ia pernah mendapatkan penghargaan penulis Asia Tenggara pada tahun 1995. Bekisar Merah awalnya terbit sebagai cerita bersambung dalam surat kabar Kompas 1993. Kemudian diterbitkan dalam bentuk buku oleh Gramedia Pustaka Utama di tahun yang sama. Novel ini telah mewakili Indonesia menerima hadiah sastra dari The S.E.A. Write Award di kota Bangkok, Thailand pada tahun 1995.',
                'foto' => 'cover_buku/bekisarmerah.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B014',
                'judul_buku' => 'Rumah Sebuah Novel',
                'pengarang' => 'Gilang Pamungkas',
                'penerbit' => 'Media Cendekia Muslim',
                'th_terbit' => '2023',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Dany georgetown',
                'edisi' => 'Cetakan pertama',
                'deskripsi_fisik' => '98 halaman ; 17 cm',
                'isbn' => '9786238367207',
                'bahasa' => 'Indonesia',
                'call_number' => '813 GIL r',
                'sinopsis' => 'Ria, seorang luxury travel planner sukses yang takut pulang. Bagi Ria, rumah adalah sumber trauma dan kebencian terhadap orang tuanya. Novel ini menarasikan perjalanan Ria menemukan makna "rumah" yang sesungguhnya—bukan sekadar bangunan, melainkan tempat memaafkan, beristirahat, dan menerima kegagalan.',
                'foto' => 'cover_buku/rumahnovel.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B015',
                'judul_buku' => 'Rumah Untuk Alie',
                'pengarang' => 'Lenn Liu ; Vie Asano ; Aira Rumi',
                'penerbit' => 'Tekad Media Cakrawala',
                'th_terbit' => '2024',
                'stok' => 2,
                'id_kategori' => 1,
                'penyunting' => 'Mardiansyah',
                'edisi' => 'Cetakan keempat',
                'deskripsi_fisik' => '262 halaman ; 20 cm',
                'isbn' => '9786230979613',
                'bahasa' => 'Indonesia',
                'call_number' => '813 LEN r',
                'sinopsis' => 'Semula, dia hidup dalam keluarga yang penuh cinta, dan rumah yang selalu memeluknya. Namun, sejak dituduh menjadi penyebab meninggalnya Bunda Gianla lima tahun lalu, segalanya berubah dalam semalam. Sebutan "pembunuh" pun disematkan dalam dirinya, dan dia terus mendapatkan penolakan dan rasa sakit dari ayah dan keempat kakaknya: Sadipta, Rendra, Samuel, dan Natta. Hidup Alie kini terasa bagai neraka. Rumah yang seharusnya menjadi tempat berlindung, malah menjadi tempat penyiksaan bagi fisik dan mentalnya. Pertanyaan ini pun kerap menghampiri Alie: sampai kapan dia harus mengalami ini semua? Akankah rumah ini kelak akan menjadi rumah lagi untuknya?',
                'foto' => 'cover_buku/rumahalie.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /*
            ===============================
            KATEGORI 2 - MAPEL
            ===============================
            */

            [
                'id_buku' => 'B016',
                'judul_buku' => 'Matematika untuk SMA/SMK Kelas X Kurikulum Merdeka',
                'pengarang' => 'Dicky Susanto, Theja Kurniawan, Savitri K. Sihombing, dkk.',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tri Hartini',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 280 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-525-8',
                'bahasa' => 'Indonesia',
                'call_number' => '510 SUS m',
                'sinopsis' => 'Materi meliputi eksponen dan logaritma, barisan dan deret, trigonometri, sistem persamaan linear, fungsi kuadrat, statistika, dan peluang.',
                'foto' => 'cover_buku/mtk10.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B017',
                'judul_buku' => 'Pendidikan Agama Islam dan Budi Pekerti untuk SMA/SMK Kelas X',
                'pengarang' => 'Ahmad Taufik, Nurwastuti Setyowati',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tim Kemendikbudristek',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 328 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-547-0',
                'bahasa' => 'Indonesia',
                'call_number' => '297 TAU p',
                'sinopsis' => 'Materi meliputi Al-Qur\'an dan Hadis, akidah, akhlak, fikih, serta sejarah peradaban Islam untuk membentuk karakter peserta didik yang beriman, bertakwa, dan berakhlak mulia.',
                'foto' => 'cover_buku/pai10.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B018',
                'judul_buku' => 'Cerdas Cergas Berbahasa dan Bersastra Indonesia untuk SMA/SMK Kelas X',
                'pengarang' => 'Fadillah Tri Aulia, Sefi Indra Gumilar',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Maman Suryaman, Priscila Fitriasih Limbong',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 250 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-324-7',
                'bahasa' => 'Indonesia',
                'call_number' => '410 AUL c',
                'sinopsis' => 'Materi meliputi berbagai jenis teks seperti laporan hasil observasi, anekdot, eksposisi, negosiasi, biografi, serta puisi untuk mengembangkan kemampuan literasi, berpikir kritis, dan keterampilan berbahasa siswa.',
                'foto' => 'cover_buku/indo10.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B019',
                'judul_buku' => 'Matematika SMK Kelas 11 Kurikulum Merdeka',
                'pengarang' => 'Dicky Susanto, dkk.',
                'penerbit' => 'Kementrian Pendidikan, Kebudayaan, Riset, dan Teknologi',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tri Hartini',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '152 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-536-4',
                'bahasa' => 'Indonesia',
                'call_number' => '510 ARI m',
                'sinopsis' => 'Materi barisan deret, trigonometri lanjutan, statistika dan peluang.',
                'foto' => 'cover_buku/mtk11.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B020',
                'judul_buku' => 'Pendidikan Agama Islam dan Budi Pekerti untuk SMA/SMK Kelas XI Kurikulum Merdeka',
                'pengarang' => 'Abd. Rahman & Hery Nugroho',
                'penerbit' => 'Kementrian Pendidikan, Kebudayaan, Riset, dan Teknologi',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Agus Imam Kharomen',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '356 halaman ; 17,6 x 25 cm',
                'isbn' => '9786020000013',
                'bahasa' => 'Indonesia',
                'call_number' => '420 OTO b',
                'sinopsis' => 'Membahas nilai-nilai keimanan, akhlak mulia, toleransi, serta penerapan ajaran Islam dalam kehidupan sehari-hari guna membentuk karakter peserta didik yang beriman dan berakhlak baik.',
                'foto' => 'cover_buku/pai11.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B021',
                'judul_buku' => 'Cerdas Cergas Berbahasa dan Bersastra Indonesia untuk SMA/SMK Kelas XI Kurikulum Merdeka',
                'pengarang' => 'Heny Marwati & K. Waskitaningtyas',
                'penerbit' => 'Kementrian Pendidikan, Kebudayaan, Riset, dan Teknologi',
                'th_terbit' => '2021',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Ahid Hidayat',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '230 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-324-7',
                'bahasa' => 'Indonesia',
                'call_number' => '410 IRM b',
                'sinopsis' => 'Membahas berbagai jenis teks dan karya sastra berbasis literasi.',
                'foto' => 'cover_buku/indoo.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B022',
                'judul_buku' => 'Matematika untuk SMA/MA Kelas XII Kurikulum Merdeka',
                'pengarang' => 'Mohammad Tohir, Ahmad Choirul Anam, Ibnu Taufiq',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2022',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tim Kemendikbudristek',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 300 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-738-2',
                'bahasa' => 'Indonesia',
                'call_number' => '510 TOH m',
                'sinopsis' => 'Materi meliputi trigonometri lanjutan, statistika, peluang, dan konsep matematika tingkat lanjut untuk mendukung pemecahan masalah dan berpikir kritis.',
                'foto' => 'cover_buku/mtk12.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B023',
                'judul_buku' => 'Pendidikan Agama Islam dan Budi Pekerti untuk SMA/SMK Kelas XII',
                'pengarang' => 'Ahmad Taufik, dkk.',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2022',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tim Kemendikbudristek',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 320 halaman ; 17,6 x 25 cm',
                'isbn' => '978-602-244-678-1',
                'bahasa' => 'Indonesia',
                'call_number' => '297 TAU p',
                'sinopsis' => 'Materi meliputi Al-Qur\'an dan Hadis, akidah, akhlak, fikih, serta sejarah Islam untuk membentuk karakter peserta didik yang beriman dan berakhlak mulia.',
                'foto' => 'cover_buku/pai12.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B024',
                'judul_buku' => 'Cerdas Cergas Berbahasa dan Bersastra Indonesia untuk SMA/SMK Kelas XII',
                'pengarang' => 'Maman Suryaman, dkk.',
                'penerbit' => 'Pusat Kurikulum dan Perbukuan, Kemendikbudristek',
                'th_terbit' => '2022',
                'stok' => 5,
                'id_kategori' => 2,
                'penyunting' => 'Tim Kemendikbudristek',
                'edisi' => 'Kurikulum Merdeka',
                'deskripsi_fisik' => '± 280 halaman ; 17,6 x 25 cm',
                'isbn' => '978-634-00-2429-6',
                'bahasa' => 'Indonesia',
                'call_number' => '410 SUR c',
                'sinopsis' => 'Materi meliputi teks argumentasi, editorial, karya ilmiah, sastra, serta penguatan literasi dan kemampuan berpikir kritis siswa.',
                'foto' => 'cover_buku/indo12.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /*
            ===============================
            KATEGORI 3 - KEJURUAN
            ===============================
            */

            [
                'id_buku' => 'B025',
                'judul_buku' => 'Rekayasa Perangkat Lunak',
                'pengarang' => 'Rosa A.S & M. Shalahuddin',
                'penerbit' => 'Informatika',
                'th_terbit' => '2018',
                'stok' => 3,
                'id_kategori' => 3,
                'penyunting' => 'Tim Editor Informatika',
                'edisi' => 'Revisi',
                'deskripsi_fisik' => '596 halaman ; 23 cm',
                'isbn' => '9786026232656',
                'bahasa' => 'Indonesia',
                'call_number' => '005.1 ROS r',
                'sinopsis' => 'Analisis dan desain sistem menggunakan UML dan manajemen proyek.',
                'foto' => 'cover_buku/rpl.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B026',
                'judul_buku' => 'Pemrograman Laravel',
                'pengarang' => 'Ade Rahmat Iskandar',
                'penerbit' => 'Gramedia',
                'th_terbit' => '2024',
                'stok' => 3,
                'id_kategori' => 3,
                'penyunting' => 'Tim Editor Gramedia',
                'edisi' => 'Cetakan pertama',
                'deskripsi_fisik' => '350 halaman ; 23 cm',
                'isbn' => '9786020000014',
                'bahasa' => 'Indonesia',
                'call_number' => '005.13 ADE p',
                'sinopsis' => 'Belajar Laravel dari dasar hingga membangun project nyata.',
                'foto' => 'cover_buku/laravel.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B027',
                'judul_buku' => 'Pemrograman Python & MySQL',
                'pengarang' => 'Abdul Kadir',
                'penerbit' => 'Elex Media',
                'th_terbit' => '2023',
                'stok' => 3,
                'id_kategori' => 3,
                'penyunting' => 'Tim Editor Elex',
                'edisi' => 'Cetakan pertama',
                'deskripsi_fisik' => '280 halaman ; 23 cm',
                'isbn' => '9786020000015',
                'bahasa' => 'Indonesia',
                'call_number' => '005.75 ABD p',
                'sinopsis' => 'Mempelajari koneksi Python dengan database MySQL dan operasi CRUD.',
                'foto' => 'cover_buku/python&mysql.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            /*
            ===============================
            KATEGORI 4 - REFERENSI
            ===============================
            */

            [
                'id_buku' => 'B028',
                'judul_buku' => 'Kamus Besar Bahasa Indonesia Edisi Kelima',
                'pengarang' => 'Pusat Bahasa Kemendikbud',
                'penerbit' => 'Balai Pustaka',
                'th_terbit' => '2016',
                'stok' => 2,
                'id_kategori' => 4,
                'penyunting' => 'Badan Pengembangan dan Pembinaan Bahasa',
                'edisi' => 'Edisi kelima',
                'deskripsi_fisik' => 'xxviii + 1628 halaman ; 27 cm',
                'isbn' => '978-979-407-182-1',
                'bahasa' => 'Indonesia',
                'call_number' => '499.221 KAM',
                'sinopsis' => 'Kamus Besar Bahasa Indonesia Edisi Kelima memuat lebih dari 90.000 lema dan sublema beserta definisi, ejaan, dan contoh penggunaannya. Merupakan rujukan utama bahasa Indonesia yang baku dan standar, disusun oleh Badan Pengembangan dan Pembinaan Bahasa.',
                'foto' => 'cover_buku/kamus.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B029',
                'judul_buku' => 'Kamus Inggris - Indonesia Edisi yang Diperbarui',
                'pengarang' => 'John M. Echols & Hassan Shadily',
                'penerbit' => 'Gramedia Pustaka Utama',
                'th_terbit' => '2014',
                'stok' => 2,
                'id_kategori' => 4,
                'penyunting' => 'John U. Wolff & James T. Collins',
                'edisi' => 'Edisi yang Diperbarui',
                'deskripsi_fisik' => 'xxxii + 824 halaman ; 23 cm',
                'isbn' => '978-602-030-564-6',
                'bahasa' => 'Indonesia & Inggris',
                'call_number' => '423.3 ECH k',
                'sinopsis' => 'Kamus Inggris-Indonesia terlengkap karya John M. Echols dan Hassan Shadily yang telah direvisi dan diperbarui. Memuat lebih dari 31.000 entri dilengkapi contoh kalimat, penjelasan arti kata dalam disiplin ilmu tertentu, dan singkatan umum dalam bahasa Inggris.',
                'foto' => 'cover_buku/kamus2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_buku' => 'B030',
                'judul_buku' => 'Ensiklopedia Sejarah Dunia',
                'pengarang' => 'Tim Usborne',
                'penerbit' => 'Bhuana Ilmu Populer',
                'th_terbit' => '2018',
                'stok' => 2,
                'id_kategori' => 4,
                'penyunting' => 'Tim Editor BIP',
                'edisi' => 'Edisi Revisi',
                'deskripsi_fisik' => 'xii + 312 halaman ; 28 cm',
                'isbn' => '9786230402678',
                'bahasa' => 'Indonesia',
                'call_number' => '900 TIM e',
                'sinopsis' => 'Ensiklopedia Sejarah Dunia ini memuat berbagai fakta dan kisah tentang berbagai bangsa, tempat, dan peristiwa pada masa lalu yang membentuk dunia. Dilengkapi skema bergambar selama 12.000 tahun, lebih dari 100 peta, ilustrasi, grafik, dan foto yang lengkap.',
                'foto' => 'cover_buku/ensiklopedia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}